<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: fbf9a83f-c277-4714-af8c-86b1784e5317
 * Migration datetime: 2021-03-03 15:25:28.106217
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrationsApplicationModule2021030315252810 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('categories', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('title')->nullable(true);
            $table->longText('description')->nullable(true);
            $table->string('slug')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('categories');
    }
}
